### ISSUE TITLE
Missing signature API SSN parameters support

### ISSUE THREAD

**Issue by ahrberg** [idfy-io/idfy-sdk-node#15]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
[POST /signature/documents](https://developer.signicat.com/express/apis/express-api.html#operation/signature/CreateDocument) support in idfy-sdk-node are missing the following options needed for SSN settings. Can this be added?

- `signers.getSocialSecurityNumber`
- `dataToSign.packaging.padesSettings.includeSsnInPades`

* **Please tell us about your environment:**
  
  - Idfy SDK version: 1.0.0-beta.7

**Comment by Slettan** [comment]
Available in 1.0.0-beta.8 :)
