### ISSUE TITLE
API returns properties in Capital Camel Case while TypeScript interface defines them as normal camel case

### ISSUE THREAD

**Issue by dariobanfi** [idfy-io/idfy-sdk-node#3]
**Note: For support questions, please contact us at support@idfy.io.**

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
The typescript interface define properties in camel case, but the API returns properties as Capital camel case

* **If the current behavior is a bug, please provide the steps to reproduce**

`const client = new IdfyClient(
    'user',
    'secret',
    ['document_read', 'identify']
  );`
`client.identification.createSession(identificationRequest)`

The object returned is `{Url: "xxxx", "RequestId: "xxx"}`, while the TypeScript interface is defined as `{url: string, requestId: string}`

* **What is the expected behavior?**

Am I missing something here?
Thanks

**Comment by Slettan** [comment]
Thanks for reporting this. While most of our APIs use camelCase, a few of our older APIs like the Identification API use Pascal Case. So the type definitions here are incorrect.

I will update the type definitions and publish a new version.

**Comment by Slettan** [comment]
Fixed in `v1.0.0-beta.2`.
